cache:
  directories:
    - node_modules
language: node_js
install:
  - npm i
script: npm run coverage --maxWorkers=4 --ci
after_script: cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
branches:
  only:
    - master
notifications:
  email: false
